name: build-windows

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  PYTHON_VERSION: 2.7
  FLAKY_TESTS: dontcare
  i18n_arg: none

jobs:
  build-windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install deps
        run: choco install nasm
      - name: Environment Information
        run: npx envinfo
      - name: Build
        run: ./vcbuild.bat
      - name: Upload Release
        uses: actions/upload-artifact@v3
        with:
          name: windows
          path: out/Release
